AssetPresets = {
    'Containers':{
        'Plastic_Bin':{
            'url':'omniverse://localhost/Projects/Medusa/bin.usd',
            'length':'0.2',
            'width':'0.1',
            'height':'0.2'
        },

        'Cardboard_Box':{
            'url':'omniverse://localhost/Projects/Medusa/Containers/CardboardBox_02.usd',
            'length':'0.7970254338452492',
            'width':'0.6365090800111943',
            'height':'0.5032872468988465'
        },

        'Cardboard_Box_Old':{
            'url':'omniverse://localhost/NVIDIA/Assets/Isaac/2023.1.1/Isaac/Environments/Simple_Warehouse/Props/SM_CardBoxA_02.usd',
            'length':'0.7970254338452492',
            'width':'0.6365090800111943',
            'height':'0.5032872468988465'
        },

        'Plastic_Bin_1':{
            'url':'https://omniverse-content-staging.s3.us-west-2.amazonaws.com/Assets/simready_content/common_assets/props/tote_b01/tote_b01.usd',
            'length':'0.6',
            'width':'0.4',
            'height':'0.4'
        },

        'Target':{
            'url':'omniverse://localhost/Projects/Medusa/CardboardBox_02.usd',
            'length':'0.7970254338452492',
            'width':'0.6365090800111943',
            'height':'0.5032872468988465'
        },    
    },

    'Products':{
        'Legos':{
            'Test': {
                'url':'omniverse://localhost/Projects/Medusa/object_1.usd',
                'length':'0.00762',
                'width':'0.00762',
                'height':'0.00508'
            },
            'Plate_1x1': {
                'url':'omniverse://localhost/Projects/Medusa/Lego/Plate_1x1.usdc',
                'length':'0.00762',
                'width':'0.00762',
                'height':'0.00508'
            },
            'Block_1x2':{
                'url':'omniverse://localhost/Projects/Medusa/Lego/Block_1x2.usdc',
                'length':'0.01524',
                'width':'0.00762',
                'height':'0.0127'
            },
            'Degree_2x2_45':{
                'url':'omniverse://localhost/Projects/Medusa/Lego/Degree_2x2_45.usdc',
                'length':'0.01524',
                'width':'0.01524',
                'height':'0.0127'
            },

            'Block_2x3':{
                'url':'omniverse://localhost/Projects/Medusa/Lego/Block_2x3.usdc',
                'length':'0.01524',
                'width':'0.02286',
                'height':'0.0127'
            },
            'Plate_2x4':{
                'url':'omniverse://localhost/Projects/Medusa/Lego/Plate_2x4.usdc',
                'length':'0.00762',
                'width':'0.01524',
                'height':'0.00508'
            },
            'Plate_6x8':{
                'url':'omniverse://localhost/Projects/Medusa/Lego/Plate_6x8.usdc',
                'length':'0.0635',
                'width':'0.04826',
                'height':'0.00508'
            },
        },
        'Loreal':{
            'Jar':{
                'url':'omniverse://localhost/Projects/Medusa/Loreal/Jar.usdc',
                'length':'',
                'width':'',
                'height':''
            },
            'Large_Bottle_1':{
                'url':'omniverse://localhost/Projects/Medusa/Loreal/Large_Bottle_1.usdc',
                'length':'',
                'width':'',
                'height':''
            },
            'Large_Bottle_2':{
                'url':'omniverse://localhost/Projects/Medusa/Loreal/Large_Bottle_2.usdc',
                'length':'',
                'width':'',
                'height':''
            },
            'Lotion_Bottle_Tall':{
                'url':'omniverse://localhost/Projects/Medusa/Loreal/Lotion_Bottle_Tall.usdc',
                'length':'',
                'width':'',
                'height':''
            },
            'Lotion_Bottle_Short':{
                'url':'omniverse://localhost/Projects/Medusa/Loreal/Lotion_Bottle_Short.usdc',
                'length':'',
                'width':'',
                'height':''
            },
        }
    }
}