[package]
version = "1.0.0"
authors = ["PENTATONIC"]
title = "Product Sort Simulator"
description="An extension that allows the user to change some settings for production sort simulation."
readme  = "docs/README.md"
category = "Simulation"
keywords = ["isaac", "genai", "llm", "simulation", "robotics"]
changelog="docs/CHANGELOG.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}

# Main python module this extension provides, it will be publicly available as "import pentatonic.productsort".
[[python.module]]
name = "pentatonic.productsort"
use_online_index = true
ignore_import_check = false

[[test]]
timeout = 960
